on:
    workflow_dispatch: 
        inputs:
            myInput:
                type: string
                description: "this string will be printed"
                required: true
                default: "First GitHubAction"


jobs:
    HelloGitHub:
        runs-on: uubuntu-18.04
        steps:
            - name: printHello
              run: |
                echo "input is"  ${{github.event.inputs.myInput}} "printed"
        
               
            
                        
                    
            
            
    

  